### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/inpainting/net_g_50000.pth'

### ISSUE THREAD

**Issue by hailianghe** [e4s2023/E4S2023#13]
How to resolve this below?

`python gradio_swap.py
/data/venv-E4S2023/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/data/E4S2023/gradio_swap.py", line 17, in <module>
    from Face_swap_with_two_imgs import FaceSwap
  File "/data/E4S2023/Face_swap_with_two_imgs.py", line 38, in <module>
    from swap_face_fine.face_inpainting import inpainting
  File "/data/E4S2023/swap_face_fine/face_inpainting.py", line 17, in <module>
    model.load_state_dict(torch.load(model_path)['params_ema'], strict=True)
  File "/data/venv-E4S2023/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/data/venv-E4S2023/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/data/venv-E4S2023/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/inpainting/net_g_50000.pth'
`

**Comment by m2nja201** [comment]
Did you download the weight files ? => https://mail2sysueducn-my.sharepoint.com/personal/yuang7_mail2_sysu_edu_cn/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fyuang7%5Fmail2%5Fsysu%5Fedu%5Fcn%2FDocuments%2Fshared%2FE4S2023
