### ISSUE TITLE
Getting Error While Starting Up

### ISSUE THREAD

**Issue by RFedz007** [e4s2023/E4S2023#2]
Hi,

I am getting this below mentioned error when starting up

(  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "D:\FaceswapOct2023\E4S2023\gradio_swap.py", line 17, in <module>
    from Face_swap_with_two_imgs import FaceSwap
  File "D:\FaceswapOct2023\E4S2023\Face_swap_with_two_imgs.py", line 11, in <module>
    from models.networks import Net3
  File "D:\FaceswapOct2023\E4S2023\models\networks.py", line 13, in <module>
    from models.stylegan2.model import EqualLinear
  File "D:\FaceswapOct2023\E4S2023\models\stylegan2\model.py", line 11, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "D:\FaceswapOct2023\E4S2023\models\stylegan2\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "D:\FaceswapOct2023\E4S2023\models\stylegan2\op\fused_act.py", line 9, in <module>
    fused = load(
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 1810, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 2242, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\cpp_extension.py", line 2382, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\vkark\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.)

Kindly Assist me how to fix this issue.

Have a Gr8 Day :)

Thank You

**Comment by ygtxr1997** [comment]
I found some related issues, see [here](https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/39).
It seems that you run the code on Windows, and you need to additionaly set `envrionment variable` by yourself to run the code following the above [method](https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/39#issuecomment-984003344).
